require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TwillioTestsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TwillioTest. As you add validations to TwillioTest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TwillioTestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all twillio_tests as @twillio_tests" do
      twillio_test = TwillioTest.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:twillio_tests)).to eq([twillio_test])
    end
  end

  describe "GET show" do
    it "assigns the requested twillio_test as @twillio_test" do
      twillio_test = TwillioTest.create! valid_attributes
      get :show, {:id => twillio_test.to_param}, valid_session
      expect(assigns(:twillio_test)).to eq(twillio_test)
    end
  end

  describe "GET new" do
    it "assigns a new twillio_test as @twillio_test" do
      get :new, {}, valid_session
      expect(assigns(:twillio_test)).to be_a_new(TwillioTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested twillio_test as @twillio_test" do
      twillio_test = TwillioTest.create! valid_attributes
      get :edit, {:id => twillio_test.to_param}, valid_session
      expect(assigns(:twillio_test)).to eq(twillio_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TwillioTest" do
        expect {
          post :create, {:twillio_test => valid_attributes}, valid_session
        }.to change(TwillioTest, :count).by(1)
      end

      it "assigns a newly created twillio_test as @twillio_test" do
        post :create, {:twillio_test => valid_attributes}, valid_session
        expect(assigns(:twillio_test)).to be_a(TwillioTest)
        expect(assigns(:twillio_test)).to be_persisted
      end

      it "redirects to the created twillio_test" do
        post :create, {:twillio_test => valid_attributes}, valid_session
        expect(response).to redirect_to(TwillioTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved twillio_test as @twillio_test" do
        post :create, {:twillio_test => invalid_attributes}, valid_session
        expect(assigns(:twillio_test)).to be_a_new(TwillioTest)
      end

      it "re-renders the 'new' template" do
        post :create, {:twillio_test => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested twillio_test" do
        twillio_test = TwillioTest.create! valid_attributes
        put :update, {:id => twillio_test.to_param, :twillio_test => new_attributes}, valid_session
        twillio_test.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested twillio_test as @twillio_test" do
        twillio_test = TwillioTest.create! valid_attributes
        put :update, {:id => twillio_test.to_param, :twillio_test => valid_attributes}, valid_session
        expect(assigns(:twillio_test)).to eq(twillio_test)
      end

      it "redirects to the twillio_test" do
        twillio_test = TwillioTest.create! valid_attributes
        put :update, {:id => twillio_test.to_param, :twillio_test => valid_attributes}, valid_session
        expect(response).to redirect_to(twillio_test)
      end
    end

    describe "with invalid params" do
      it "assigns the twillio_test as @twillio_test" do
        twillio_test = TwillioTest.create! valid_attributes
        put :update, {:id => twillio_test.to_param, :twillio_test => invalid_attributes}, valid_session
        expect(assigns(:twillio_test)).to eq(twillio_test)
      end

      it "re-renders the 'edit' template" do
        twillio_test = TwillioTest.create! valid_attributes
        put :update, {:id => twillio_test.to_param, :twillio_test => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested twillio_test" do
      twillio_test = TwillioTest.create! valid_attributes
      expect {
        delete :destroy, {:id => twillio_test.to_param}, valid_session
      }.to change(TwillioTest, :count).by(-1)
    end

    it "redirects to the twillio_tests list" do
      twillio_test = TwillioTest.create! valid_attributes
      delete :destroy, {:id => twillio_test.to_param}, valid_session
      expect(response).to redirect_to(twillio_tests_url)
    end
  end

end
